AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
Metrics/LineLength:
  Max: 120
Style/AsciiComments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/BlockComments:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 30
Style/StringLiterals:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
